server:
  port: 8081

friends:
  lastName: zhangsan
  age: 22

friends2: {lastName: zhangsan, age: 22}

pets:
  - cat
  - dog
  - pig

pets2: [cat, dog, pig]

#person:
#  name: roy
#  boss: false
#  birth: 2017/01/01
#  maps: {k1: v1, k2: 12}
#  lists:
#    - lisi
#    - zhangsan
#    - wangwu
#  dog:
#    name: wangwang
#    age: 3
#  age: 33