server:
  port: 8080
  config:
    location: G:/application.properties
  http:
    encoding:
      enabled: true
      charset: utf-8


person:
  name: roy${random.int}
  boss: false
  birth: 2017/01/01
  maps: {k1: v1, k2: 12}
  lists:
    - lisi
    - zhangsan
    - wangwu
  dog:
    name: ${person.name}'s dog
    age: 3
  age: 33

spring:
  messages:
    basename: i18n.index
#  禁用thymeleaf缓存
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd



#开启SpringBoot的debug模式
#debug: true


---
server:
  port: 8082
spring:
  profiles: dev1

---
server:
  port: 8084
spring:
  profiles: prod1
