server:
  port: 8081
spring:
  profiles:
    active: dev1
  config:
    location: G:/application.properties


person:
  name: roy${random.int}
  boss: false
  birth: 2017/01/01
  maps: {k1: v1, k2: 12}
  lists:
    - lisi
    - zhangsan
    - wangwu
  dog:
    name: ${person.name}'s dog
    age: 3
  age: 33

---
server:
  port: 8082
spring:
  profiles: dev1

---
server:
  port: 8084
spring:
  profiles: prod1
